FROM python:3.10-slim

WORKDIR /opt/dagster/app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p $DAGSTER_HOME
RUN mkdir -p /opt/dagster/app/src

# Set working directory to allow the daemon and webserver to find the workspace correctly
WORKDIR /opt/dagster/app
