#!/bin/sh
# Installe les hooks git de ce clone (garde-fous), puis verifie l'installation.
#
# Appele par `make install`. Git n'execute rien de ce qui arrive avec un clone :
# l'installation est forcement un geste local. Le script fait les deux etapes
# dans le bon ordre et sort en erreur si le resultat n'est pas celui attendu,
# car un ordre inverse ne produit aucune erreur, seulement l'absence d'une
# protection.
#
# Ordre des etapes :
#
#   1. le controle d'identite (scripts/git-hooks/pre-commit) est copie dans le
#      repertoire des hooks ;
#   2. `pre-commit install`, sans -f, deplace cette copie en `<type>.legacy`,
#      l'execute avant ses propres hooks, et s'installe par-dessus.
#
# Dans l'ordre inverse, la copie ecraserait le hook du framework, et seul le
# controle d'identite resterait.
#
# Pourquoi la copie `.legacy` : le hook du framework lit sa configuration en
# chemin relatif (`--config=.pre-commit-config.yaml`), donc dans l'arbre de
# travail. Un controle declare dans ce fichier ne s'applique pas apres un
# `git checkout` d'un commit ancien, un `git bisect` ou un HEAD detache dont la
# configuration ne le porte pas (`mesure` le 31 aout 2026 : aucun des 111
# commits de `main` d'alors ne le portait). `<type>.legacy` vit hors de l'arbre
# de travail et s'applique a tout commit.
#
# Ne jamais passer -f : `pre-commit install` le suggere (« Use -f to use only
# pre-commit. »), mais -f supprime la copie `.legacy`. La verification finale
# echoue si elle a disparu.
set -eu

racine=$(git rev-parse --show-toplevel)
cd "$racine"

# `--git-common-dir` et non `--git-dir` : dans un arbre de travail secondaire,
# `--git-dir` rend `.git/worktrees/<nom>`, qui n'heberge aucun hook. Les hooks
# vivent dans le repertoire commun a tous les arbres de travail : une seule
# installation par clone.
commun=$(cd "$(git rev-parse --git-common-dir)" && pwd)
identite="$racine/scripts/git-hooks/pre-commit"

# Les types de hook a installer. `pre-commit` seul ne couvre pas les commits de
# fusion : `git merge --no-ff` declenche `pre-merge-commit`,
# `prepare-commit-msg` et `commit-msg`, jamais `pre-commit` (`mesure` le 31 aout
# 2026). Le controle d'identite est copie sur les deux types, pour que
# `<type>.legacy` couvre aussi les fusions sur une branche dont la
# configuration ne declare pas le hook.
TYPES="pre-commit pre-merge-commit"

# Une liste vide est refusee. La boucle de verification, plus bas, itere la
# meme variable : vide, elle ne verifierait rien, et le script sortirait en 0
# sans aucune copie `.legacy`. Le framework resterait installe (sans
# `--hook-type`, `pre-commit install` retombe sur `default_install_hook_types`),
# ce qui masquerait l'absence. Teste par
# tests/unit/test_installation_des_garde_fous.py.
if [ -z "$TYPES" ]; then
    echo "ECHEC : aucun type de hook a armer (TYPES est vide)." >&2
    exit 1
fi

if [ ! -f "$identite" ]; then
    echo "ECHEC : $identite est introuvable." >&2
    exit 1
fi

mkdir -p "$commun/hooks"
for type in $TYPES; do
    cp "$identite" "$commun/hooks/$type"
    chmod +x "$commun/hooks/$type"
done

# `PRE_COMMIT` sert au test de ce script
# (`tests/unit/test_installation_des_garde_fous.py`), qui monte un depot
# temporaire hors du projet `uv` et doit nommer l'executable lui-meme. La valeur
# par defaut est celle qu'utilise `make install`.
pre_commit="${PRE_COMMIT:-uv run pre-commit}"

arguments=""
for type in $TYPES; do
    arguments="$arguments --hook-type $type"
done

# Les types sont passes explicitement plutot que laisses a
# `default_install_hook_types` : cette cle vit dans `.pre-commit-config.yaml`,
# donc dans l'arbre de travail, et l'installation ne doit pas dependre de la
# branche sortie au moment ou elle s'execute.
# shellcheck disable=SC2086
if ! $pre_commit install $arguments; then
    echo "ECHEC : « $pre_commit install » a rendu une erreur." >&2
    echo "Le controle d'identite est copie et actif ; les hooks du framework" >&2
    echo "ne le sont pas. Corrige la cause, puis relance : make install" >&2
    exit 1
fi

# Verification : constate l'installation au lieu de la supposer.
erreurs=0
for type in $TYPES; do
    genere="$commun/hooks/$type"
    legacy="$commun/hooks/$type.legacy"

    if ! grep -q 'generated by pre-commit' "$genere" 2>/dev/null; then
        echo "ECHEC : $genere n'est pas le hook du framework." >&2
        echo "  Cause probable : la copie manuelle est passee APRES" >&2
        echo "  « pre-commit install » et l'a ecrase." >&2
        erreurs=1
    fi

    if ! cmp -s "$identite" "$legacy"; then
        echo "ECHEC : $legacy ne porte pas le controle d'identite." >&2
        echo "  Cause probable : « pre-commit install -f », qui supprime la" >&2
        echo "  seule couche independante de l'arbre de travail." >&2
        erreurs=1
    fi
done

if [ "$erreurs" -ne 0 ]; then
    echo "" >&2
    echo "Les garde-fous ne sont PAS armes. Ne commite pas avant d'avoir" >&2
    echo "corrige : le controle d'identite est celui dont l'oubli a coute un" >&2
    echo "depot entier (documentation/pilotage_du_chantier.md, §2.1)." >&2
    exit 1
fi

echo "Garde-fous armes dans $commun/hooks :"
for type in $TYPES; do
    echo "  $type          hooks du framework (.pre-commit-config.yaml)"
    echo "  $type.legacy   controle d'identite, valable pour toute branche"
done
